integration:
  genderize:
    url: https://api.genderize.io/

spring:
  application:
    name: nexxiot
  datasource:
    url: jdbc:postgresql://localhost:5432/nexxiot
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: always
  flyway:
    enabled: true