spring:
    application:
        name: nexxiot
    datasource:
        url: jdbc:postgresql://localhost:5432/nexxiot
        username: postgres
        password: root
    jpa:
        hibernate:
            ddl-auto: update